apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-service
  labels:
    app: sample-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - env:
        - name: spring.data.mongodb.host
          value: mongo
        image: everisbham/sample-service
        name: sample-service
        ports:
        - containerPort: 8080
          name: http-server